services:
  - type: web
    name: emotion-api
    env: docker
    region: oregon
    plan: standard
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_KEYS_FILE
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
    autoDeploy: true 